FROM node:alpine
RUN chown node:node ./
USER node

WORKDIR /app

# copyies package-lock.json and package.json
COPY package*.json ./

# install dependencies
RUN npm ci && npm cache clean --force

# copy everything over to environment
COPY . .

RUN chown node:node ./
USER node

CMD ["npm", "start"]