version: "3.8"
services:
  cache:
    image: redis:alpine
    ports:
      - 6379:6379    
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - dd_database:/data/db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      # Bind code in container to local src code to support hot-reloading
      - "./frontend/src:/app/src"
      - "./frontend/public:/app/public"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_ADDRESS=db
      - CACHE_ADDRESS=cache
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5500:80"
    depends_on:
      - frontend
      - server
      - db
      - cache
volumes:
  dd_database: