version: "3.8"
services:
  db:
    image: rethinkdb:latest
    ports:
      - 8080:8080
      - 29015:29015
      - 28015:28015
    volumes:
      - "./rethinkdb_data:/data/rethinkdb_data"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_ADDRESS=db
    ports:
      - '8000:8000'
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5500:80"
    depends_on:
      - frontend
      - server
      - db
