version: "3.8"
services:
  cache:
    image: redis:alpine
    command: "redis-server --requirepass ${REDIS_PASSWORD} --protected-mode yes"
    ports:
      - 6379:6379    
    volumes:
      - ./redis_data:/data/redis_data
  db:
    image: rethinkdb:latest
    ports:
      - 8080:8080
      - 29015:29015
      - 28015:28015
    volumes:
      - "./rethinkdb_data:/data/rethinkdb_data"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      # Bind code in container to local src code to support hot-reloading
      - "./frontend/src:/app/src"
      - "./frontend/public:/app/public"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_ADDRESS=db
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - CACHE_ADDRESS=cache
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5500:80"
    depends_on:
      - frontend
      - server
      - db
      - cache
