version: "3.8"
services:
  cache:
    image: redis:alpine
    command: "redis-server --requirepass ${REDIS_PASSWORD} --protected-mode yes"
    restart: unless-stopped
    volumes:
      - ./data/redis_data:/data/redis_data
 server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_ADDRESS=$MONGO_ADDRESS
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - CACHE_ADDRESS=cache
      - DEBUG_MESSAGES=false
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - server
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - server
      - cache
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"''' # Reload auto-renewed ssl certificates
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'" # Check for auto-renew every 12 hours
